feat: comment 생성하기 (memberId는 인증 후 적용)
potato-club/national-petition-backend pull request #4
Opened 2021-09-13 04:28 UTC by yerimkoko

memberId는 인증 기능 이후 적용을 해서 임시로 dto 에 넣어뒀습니다

2021-09-13 05:24 UTC, seungh0 requested changes

2021-09-13 05:24 UTC, seungh0 commented on src/main/java/com/example/nationalpetition/dto/CommentCreateDto.java
> +    public Comment toEntity(Long memberId, Long boardId) {
나중에 인증 붙이고 바뀌겠지만

지금 memberId는 매개변수로 안받고 클래스의 멤버변수를 쓰면 되지 않을까여?

2021-09-13 05:24 UTC, seungh0 commented on src/test/java/com/example/nationalpetition/serviceTest/CommentServiceTest.java
> +        Comment comment = commentRepository.findAll().get(0);
굿!

2021-09-13 05:24 UTC, seungh0 commented on src/test/java/com/example/nationalpetition/serviceTest/CommentServiceTest.java
> +        Comment comment = commentRepository.findAll().get(0);
부모 댓글이 있는 댓글 작성도 테스트해보면 좋을거 같네여!

2021-09-13 05:24 UTC, seungh0 commented on src/main/java/com/example/nationalpetition/domain/comment/Comment.java
> +        this.depth = 0;
depth가 항상 0이진 않을거 같아요!

자식 댓글 생성시 depth 테스트도 추가해보시죠

2021-09-13 05:24 UTC, seungh0 commented on src/main/java/com/example/nationalpetition/domain/comment/Comment.java
> +        this.depth = 0;
부모가 있는 댓글을 생성하는 인스턴스
부모가 없는(???) 댓글을 생성하는 댓글을 생성하는 인스턴스

별도의 정적팩토리 메소드가 있으면, 더 이해하기 쉬울거 같아요!

ex) newRootComment(), newChildComment()

2021-09-13 05:24 UTC, seungh0 commented on src/main/java/com/example/nationalpetition/domain/comment/Comment.java
> +        this.depth = 0;
어떤 느낌이냐면 다른 개발자가 서비스 레이어 입장에서 Comment 도메인의 세부 구현을 몰라도 newRootComment()에 필요한 매개변수와 함께 호출하면 최상위 댓글 인스턴스가 생성되겠구나~

이런식으로 추상화하는것이 좋습니다

2021-09-13 05:24 UTC, seungh0 commented on src/main/java/com/example/nationalpetition/controller/comment/CommentController.java
> +    public ApiResponse<Long> save(@RequestBody CommentCreateDto dto, @PathVariable Long boardId){
서비스 메소드도 그렇고 좀 더 비즈니스 네이밍이 좋을거 같아요.
addComment() 같은??

2021-09-13 05:24 UTC, seungh0 commented on src/main/java/com/example/nationalpetition/controller/comment/CommentController.java
> +    private final CommentService service;
나중에 여러 서비스를 의존할 수 있는데 commentService로 이름을 짓는것이 좋을거 같네요!
(나중에 변경하기 번거로우므로)

2021-09-13 06:13 UTC, YuSunjo commented on src/main/java/com/example/nationalpetition/domain/comment/Comment.java
> +        this.depth = 0;
오호  근데 혹시 나중에 쿼리를 parentId로 groupBy할건가요? 나중에 리스트로 프론트에 response 해줄 때 어떻게 뿌려줄건지 궁금합니다!

2021-09-13 14:00 UTC, hyun6ik approved these changes

2021-09-13 14:00 UTC, hyun6ik commented on src/test/java/com/example/nationalpetition/serviceTest/CommentServiceTest.java
> +        Comment comment = commentRepository.findAll().get(0);
void 댓글을_저장한다라고 해서 상관없지만 @DisplayName 애노테이션을 사용하는게 더 명확해 보여서 좋을것 같구 
레포지토리에서 findAll 해서 제일 앞에 있는 값을 받는거보단 save하고 받환 받은 값으로 레포지토리에서 댓글을 찾는게 더 저는 명확하다고 생각합니다!!

2021-09-13 18:02 UTC, seungh0 commented on src/test/java/com/example/nationalpetition/serviceTest/CommentServiceTest.java
> +        Comment comment = commentRepository.findAll().get(0);
@DisplayName 쓰면 영어로 메소드 이름 짓고, 한글로도 이름 짓는 두 번에 걸쳐서 이름을 지어서 전 댓글을_저장한다() 처럼 합니다

2021-09-14 17:44 UTC, seungh0 commented on src/test/java/com/example/nationalpetition/serviceTest/CommentServiceTest.java
> +        Comment comment = commentRepository.findAll().get(0);
1. 게시물이 DB에 한개 저장되는지
2. 게시물 정보가 DB에 정확하게 저장되는지

이 두개가 가장 중요한 테스트일 것 같은데 어떤 테스트 코드를 작성하면 좋을지 생각해보시면 좋을 것 같습니당

2021-09-17 04:10 UTC, seungh0 approved these changes

2021-09-17 04:10 UTC, seungh0 commented on build.gradle
> +
요거 뺴주세용

2021-09-17 04:10 UTC, seungh0 commented on src/main/java/com/example/nationalpetition/domain/comment/Comment.java
> +    @ColumnDefault("0")
??? 이게 뭔가용?

2021-09-17 05:00 UTC, closed without merging